# Generated by Django 3.0.5 on 2021-06-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yauser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
