# Generated by Django 3.0.5 on 2021-06-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_yauser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='yauser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
