# Generated by Django 3.0.5 on 2021-06-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210619_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yauser',
            name='is_verified',
        ),
    ]
