# Generated by Django 3.0.5 on 2021-06-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210615_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yauser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Username'),
        ),
    ]
