# Generated by Django 3.0.5 on 2021-06-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210621_1830'),
        ('api', '0004_remove_yauser_is_verified'),
    ]

    operations = [
    ]
